apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  Route53AccessKeyId: {{ .Values.Route53AccessKeyId | b64enc }}
  Route53SecretAccessKey: {{ .Values.Route53SecretAccessKey | b64enc }}
