apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: zambonigirl-com-ddns-route53
  name: zambonigirl-com-ddns-route53
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zambonigirl-com-ddns-route53
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: zambonigirl-com-ddns-route53
    spec:
      containers:
        - env:
            - name: DDNSR53_CREDENTIALS_ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  key: Route53AccessKeyId
                  name: {{ .Release.Name }}-auth
            - name: DDNSR53_CREDENTIALS_SECRETACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: Route53SecretAccessKey
                  name: {{ .Release.Name }}-auth
            - name: DDNSR53_ROUTE53_HOSTEDZONEID
              value: Z00982152R6JWYT6DR9H0
            - name: DDNSR53_ROUTE53_RECORDSSET_0_NAME
              value: zambonigirl.com.
            - name: DDNSR53_ROUTE53_RECORDSSET_0_TTL
              value: "300"
            - name: DDNSR53_ROUTE53_RECORDSSET_0_TYPE
              value: A
            - name: DDNSR53_ROUTE53_RECORDSSET_1_NAME
              value: '*.zambonigirl.com.'
            - name: DDNSR53_ROUTE53_RECORDSSET_1_TTL
              value: "300"
            - name: DDNSR53_ROUTE53_RECORDSSET_1_TYPE
              value: A
            - name: LOG_JSON
              value: "false"
            - name: LOG_LEVEL
              value: info
            - name: SCHEDULE
              value: '*/30 * * * *'
            - name: TZ
              value: Europe/Paris
          image: docker.io/crazymax/ddns-route53:latest
          name: zambonigirl-com-ddns-route53
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
status: {}
